version: '3'

services:
  system-hello_ixc_world:
    build:
      context: .
      args:
        IMAGE: ubuntu:16.04
        USER: helloflag
        TIMEOUT: 60
        EXEC: hello_flag_exec
        SERVICE: hello_flag
        APT_OLD: 0
    ports:
      - "10001:10001"
    restart: always
